FROM condaforge/mambaforge:24.9.2-0 as builder
#LABEL maintainer "Ciheim Brown"
## Description ##
# condaforge is based on a stripped down ubuntu image.  We need some extra bits for frerun + fremake
####

# Set where the conda installation goes
ARG conda_location=/app/cylc-flow-tools

# Change to encrypted HTTP
RUN sed -i 's/http/https/g' /etc/apt/sources.list

# apt installs to /usr/bin/
RUN apt update \
  && apt -y install uuid-runtime time csh python bc 

# Update conda because this build container may be stale.
RUN conda update -n base -c conda-forge conda

# Copy runscript in container and make it executable
COPY ppp_files/runscript.sh /app/exec/runscript.sh
RUN chmod +x /app/exec/runscript.sh

# Set up conda environment directory for cylc workflow
COPY ppp_files/cylc-flow-tools.yaml ${conda_location}/cylc-flow-tools.yaml
RUN mamba env create --file ${conda_location}/cylc-flow-tools.yaml -p ${conda_location}

# Maybe perhaps tag an external mounted volume /mnt2 as being safe...
# RUN git config --global --add safe.directory /mnt2

RUN conda install urwid==2.*

ENTRYPOINT ["/bin/bash"]
