workflow:
  rules:
  - if: '$CI_PROJECT_PATH != "fre/HPC-ME"'
    when: never
  - when: always
  auto_cancel:
    on_new_commit: interruptible

default:
  tags: [hpc-me]
  interruptible: true

stages:
  - routing

trigger-build:
  # Route to the build pipeline for Merge Requests
  stage: routing
  trigger:
    include: .gitlab-ci-builds.yml
    strategy: depend
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

trigger-clean:
    # Route to the cleanup pipeline ONLY if triggered by a schedule
    stage: routing
    trigger:
      include: .gitlab-ci-cleanup.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'