FROM ecpe4s/ubuntu20.04-oneapi-x86_64:22.02

COPY /spack_intel_ubuntu20.04_e4s.yaml /spack.yaml

RUN apt-get update -y
RUN apt-get install -y patch

RUN export SPACK_DISABLE_LOCAL_CONFIG=1 \
 && export SPACK_USER_CACHE_PATH=/tmp/_spack_cache \
 && . /spack/share/spack/setup-env.sh \
 && spack -e . concretize -f | tee concretize.log \
 && spack -e . buildcache keys -it \
 && spack -e . install --cache-only \
 && spack clean -a

RUN echo module purge >> /etc/bash.bashrc
