# Build stage with Spack pre-installed and ready to be used
FROM intel/oneapi-hpckit:2021.4-devel-centos8 as builder

RUN mkdir /opt/spack-environment

# What we want to install and how we want to install it
# # is specified in a manifest file (spack.yaml)
COPY spack_intel_centos8.yaml /opt/spack-environment/spack.yaml 


#RUN yum update -y
RUN yum install -y python36-devel.x86_64 
RUN yum install -y libstdc++-static
RUN yum install -y git
RUN yum install -y patch
RUN yum install -y diffutils
RUN yum install -y file


# Setup spack
# these instructions are from one of the current non-runner ecpe4s dockerhub images
RUN git clone https://github.com/spack/spack.git \
    && cd spack \
    && git checkout c24413a530ee4cddc630d79aa67fada7d82a86e5 

# Install the software, remove unnecessary deps --fail-fast
RUN cd /opt/spack-environment && \
    . /spack/share/spack/setup-env.sh && \
    spack compiler find && \
    spack env create -d . && \
    spack env activate . && \
    yum install -y cpio && \ 
    spack install --dirty && \
    spack gc -y 

# Modifications to the environment that are necessary to run
RUN . /etc/skel/.bashrc && \ 
    cd /opt/spack-environment && \
    . /opt/intel/oneapi/setvars.sh && \
    . /spack/share/spack/setup-env.sh && \ 
    spack env activate --sh -d . >> /etc/profile.d/z10_spack_environment.sh
#
# Bare OS image to run the installed executables
FROM intel/oneapi-hpckit:2021.4-devel-centos8 

COPY --from=builder /opt /opt
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/profile.d/z10_spack_environment.sh

#RUN yum update
RUN yum install -y git
RUN yum install -y autoconf
RUN yum install -y libtool

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l"]

