FROM intel/oneapi-runtime:2024.2.1-0-devel-ubuntu22.04 as final

FROM intel/oneapi-runtime:latest as final
COPY --from=builder /opt/software /opt/software
COPY --from=builder /opt/views /opt/views

ENV LD_LIBRARY_PATH /opt/views/view/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH /opt/views/view/lib:$LIBRARY_PATH
ENV PATH $PATH:/opt/views/view/bin
ENTRYPOINT [ "/bin/bash" ]
