# Build stage with Spack pre-installed and ready to be used
FROM ecpe4s/rhel8-runner-x86_64:2021-09-01-gcc11.2 as builder

RUN mkdir /opt/spack-environment

# What we want to install and how we want to install it
# # is specified in a manifest file (spack.yaml) 
COPY spack_gnu.yaml /opt/spack-environment/spack.yaml

# Setup spack
# these instructions are from one of the current non-runner ecpe4s dockerhub images
RUN git clone https://github.com/spack/spack.git \
     && cd spack \
     && git checkout c24413a530ee4cddc630d79aa67fada7d82a86e5

# Install the software, remove unnecessary deps
RUN cd /opt/spack-environment && \
    . /spack/share/spack/setup-env.sh && \
    spack compiler find && \ 
    spack env create -d . && \
    spack env activate . && \ 
    spack install --dirty && \
    spack gc -y

# Strip all the binaries
RUN find -L /opt/view/* -type f -exec readlink -f '{}' \; | \
    xargs file -i | \
    grep 'charset=binary' | \
    grep 'x-executable\|x-archive\|x-sharedlib' | \
    awk -F: '{print $1}' | xargs strip -s

# Modifications to the environment that are necessary to run
RUN cd /opt/spack-environment && \
    . /spack/share/spack/setup-env.sh && \
    spack env activate --sh -d . >> /etc/profile.d/z10_spack_environment.sh


# Bare OS image to run the installed executables
FROM ecpe4s/rhel8-runner-x86_64:2021-09-01-gcc11.2

COPY --from=builder /opt/spack-environment /opt/spack-environment
COPY --from=builder /opt/software /opt/software
COPY --from=builder /opt/view /opt/view
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/profile.d/z10_spack_environment.sh



ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l"]
