FROM intel/oneapi-hpckit:2025.1.0-0-devel-ubuntu24.04 as builder
############## Set up build environment#################
# Add packages needed for building software stack 
RUN apt-get update -y \
 && apt-get upgrade -y \
 && apt-get install -y autoconf automake libtool cmake autoconf-archive build-essential wget git
## Clone spack
RUN mkdir -p /opt && cd /opt && git clone -b v0.23.1 https://github.com/spack/spack.git
# What we want to install and how we want to install it
# is specified in a manifest file (spack.yaml)
RUN mkdir -p /opt/spack-environment && \
set -o noclobber \
&&  (echo spack: \
&&   echo '  mirrors:'\
&&   echo '    E4S: https://cache.e4s.io/noaa'\
&&   echo '  definitions:' \
&&   echo '  - packages_builtin:' \
&&   echo '    - bacio%oneapi@2025.1.0' \
&&   echo '    - hdf5@1.14.3%oneapi@2025.1.0' \
&&   echo '    - ip%oneapi@2025.1.0' \
&&   echo '    - libyaml@0.2.5%oneapi@2025.1.0' \
&&   echo '    - nccmp@1.9.1.0%oneapi@2025.1.0' \
&&   echo '    - netcdf-c@4.9.2%oneapi@2025.1.0' \
&&   echo '    - netcdf-fortran@4.6.1%oneapi@2025.1.0' \
&&   echo '    - sp@2.3.3%oneapi@2025.1.0' \
&&   echo '    - w3emc@2.11.0' \
&&   echo '    - w3nco@2.4.1' \
&&   echo '    - zlib%oneapi@2025.1.0' \
&&   echo '    - zlib-ng@2.1.4%oneapi@2025.1.0' \
&&   echo '  packages:' \
&&   echo '    hdf5:' \
&&   echo '      variants: +fortran+hl+szip~~mpi' \
&&   echo '    netcdf-c:' \
&&   echo '      variants: +dap~~mpi' \
&&   echo '    pango:' \
&&   echo '      variants: +X~~mpi' \
&&   echo '    cmake:' \
&&   echo '      externals:' \
&&   echo '      - spec: "cmake@3.28.3"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    automake:' \
&&   echo '      externals:' \
&&   echo '      - spec: "automake@1.16.5"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    binutils:' \
&&   echo '      externals:' \
&&   echo '      - spec: "binutils@2.42"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    diffutils:' \
&&   echo '      externals:' \
&&   echo '      - spec: "diffutils@3.10"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    gmake:' \
&&   echo '      externals:' \
&&   echo '      - spec: "gmake@4.3"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    libtool:' \
&&   echo '      externals:' \
&&   echo '      - spec: "libtool@2.4.7"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    m4:' \
&&   echo '      externals:' \
&&   echo '      - spec: "m4@1.4.19"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    perl:' \
&&   echo '      externals:' \
&&   echo '      - spec: "perl@5.38.2"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    tar:' \
&&   echo '      externals:' \
&&   echo '      - spec: "tar@1.35"' \
&&   echo '        prefix: "/usr"' \
&&   echo '      buildable: False' \
&&   echo '    all:' \
&&   echo '      target: [x86_64]' \
&&   echo '      providers:' \
&&   echo '        zlib-api: [zlib-ng+compat, zlib]' \
&&   echo '      compiler: [oneapi]' \
&&   echo '  specs:' \
&&   echo '  - matrix:' \
&&   echo '    - [$packages_builtin]' \
&&   echo '  concretizer:' \
&&   echo '    unify: True' \
&&   echo '  config:' \
&&   echo '    install_tree: /opt/software' \
&&   echo '  view: /opt/views/view') > /opt/spack-environment/spack.yaml
# Install the software, remove unnecessary deps 
RUN . /opt/spack/share/spack/setup-env.sh && cd /opt/spack-environment && spack compiler add && spack --verbose env activate . && spack --verbose install --fail-fast && spack gc -y

ENV LD_LIBRARY_PATH /opt/views/view/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH /opt/views/view/lib:$LIBRARY_PATH
ENV PATH /opt/views/view/bin:$PATH
ENTRYPOINT [ "/bin/bash" ]

