FROM ubuntu:24.04
RUN apt-get update && apt-get install -y csh bash git which eval readlink python3 getopt 
RUN apt-get install -y miniconda
RUN conda create -n env \
 && conda install -n env nco cdo R udunits \
 && conda init
RUN mkdir -p /apps \
 && cd /apps \
 && git clone https://gitlab.gfdl.noaa.gov/esd/fudge.git  
RUN mkdir -p /home/esd/bin/ \
 && cp /apps/fudge/checkout-fudge /home/esd/bin/
ENV PATH ${PATH}:/home/esd/bin:/apps/fudge/bin
