FROM continuumio/miniconda3:25.3.1-1 as builder
RUN sed -i -e 's/http:/https:/g' /etc/apt/sources.list.d/debian.sources
RUN apt-get update -y \
 && apt-get install -y csh tcsh which 
RUN conda create -y -n env \
 && conda install -n env conda-forge::nco=5.1.9 conda-forge::r=4.2 conda-forge::cdo=2.4.0 python=3.10 numpy \
 && conda install -n env r-base \
 && conda init
RUN mkdir -p /apps/fudge \
 && cd /apps 
RUN git clone --depth 1 --branch pistachio-07291411 https://gitlab.gfdl.noaa.gov/esd/fudge.git /apps/fudge 
RUN ls /apps/fudge
RUN mkdir -p /home/esd/bin/ \
 && cp /apps/fudge/checkout-fudge /home/esd/bin/
ENV PATH="/home/esd/bin:/apps/fudge/bin:/opt/conda/envs/env/bin:$PATH"
SHELL ["/bin/tcsh", "-c"]
RUN echo 'source activate env' >> ~/.cshrc
ENV SHELL container 
RUN mkdir -p /tmpdir
RUN /bin/tcsh -c eval `apps/fudge/checkout-fudge --checkout-dir /tmpdir --fudgetag pistachio-07291411`
RUN conda run -n env Rscript -e "install.packages('optparse', repos='https://cloud.r-project.org/')"
RUN cp -r /tmpdir/pistachio-07291411 /apps/
RUN chmod -R 777 /apps
ENV PYTHONPATH="${PYTHONPATH}:/apps/fudge/utils/aux:/apps/fudge/utils/bin:/apps/fudge/utils/pp:/apps/fudge/bin:/apps/fudge:/apps/fudge/utils/shared_code"
ENV BASEDIR="/apps/pistachio-07291411/fudge/" 
ENV FUDGETAG="pistachio-07291411"
ENV FUDGE_ENV="/apps/pistachio-07291411/fudge/environment_info.csh"
RUN python -c "import sys; print(sys.path)"
ENTRYPOINT ["/bin/tcsh"]
CMD ["tcsh", "-i"]
