# Build stage with Spack pre-installed and ready to be used
FROM intel/oneapi-hpckit:2022.1.1-devel-ubuntu18.04 as builder

RUN mkdir /opt/spack-environment

# What we want to install and how we want to install it
# # is specified in a manifest file (spack.yaml)
COPY spack_intel_ubuntu.yaml /opt/spack-environment/spack.yaml
RUN apt-get update -y
RUN apt-get install -y git
RUN apt-get install -y perlbrew
RUN apt-get install -y csh
RUN apt-get install -y uuid-runtime
RUN apt-get install -y time
# Setup spack
# these instructions are from one of the current non-runner ecpe4s dockerhub images
RUN git clone https://github.com/spack/spack.git \
    && cd spack \
    && git checkout v0.17.1

RUN git clone https://gitlab.gfdl.noaa.gov/fre/HSM.git 

RUN git clone https://github.com/hookbot/File-NFSLock

RUN cp /HSM/mk/gfdl.inc /HSM/mk/containers.inc

RUN sed -i '32,46d' /HSM/mk/containers.inc

RUN sed -i 's/r > 0/r > 1/g' /HSM/lib/HSM.pm

ENV HSM_HOME=/HSM 
ENV HSM_SITE=containers 
ENV HSM_VERSION=HPC-ME  
ENV PATH=/HSM/bin:$PATH 
ENV PERL5LIB=/File-NFSLock/lib:/HSM/lib:/usr/share/perl/5.26.1 
ENV MANPATH=/HSM/man:$MANPATH


# module load perlbrew

# Install the software, remove unnecessary deps --fail-fast
#RUN . /opt/intel/oneapi/setvars.sh && \
