FROM continuumio/miniconda3:25.3.1-1 as builder
RUN sed -i -e 's/http:/https:/g' /etc/apt/sources.list.d/debian.sources
RUN apt-get update -y \
 && apt-get install -y csh tcsh which 
RUN conda create -n env \
 && conda install -n env conda-forge::nco=5.1.9 conda-forge::r=4.2 conda-forge::cdo=2.4.0 python=2.7 numpy \
 && conda init
RUN mkdir -p /apps \
 && cd /apps \
 && git clone -b http https://gitlab.gfdl.noaa.gov/esd/fudge.git  
RUN mkdir -p /home/esd/bin/ \
 && cp /apps/fudge/checkout-fudge /home/esd/bin/
ENV PATH ${PATH}:/home/esd/bin:/apps/fudge/bin
SHELL ["/bin/tcsh", "-c"]
RUN conda init 
SHELL ["conda", "run", "-n", "env", "/bin/tcsh", "-c"]
ENV SHELL container 
RUN /bin/tcsh -c eval `apps/fudge/checkout-fudge --fudgetag oreo-20250402`
SHELL ["conda", "activate", "-n", "env", "/bin/tcsh", "-c"]
ENTRYPOINT [ "/bin/tcsh" ]
