## must be triggered manually to push image
name: Build and Push FMS CI Image (GNU)
on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the pushed image, usually the compiler version"
        required: true
jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io 
    - name: Build and Push Image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ci/fms-gnu 
        push: true
        tags: "ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:${{ github.event.inputs.version }}"
        file: "Dockerfile"
